# Generated by Django 4.2.7 on 2024-12-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('Accepted', 'Accepted')], default='Assigned', max_length=20)),
                ('deadline', models.DateField()),
            ],
        ),
    ]
