# Generated by Django 5.1.4 on 2024-12-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_project_assigned_to_project_date_project_total_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='makrs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('accepted', 'Accepted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('accepted', 'Accepted')], default='pending', max_length=20),
        ),
    ]
