# Generated by Django 5.1.4 on 2024-12-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_project_makrs_alter_project_status_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='makrs',
            new_name='marks',
        ),
    ]
